name: Build RISC-V Toolchain RV64 Newlib for MacOS

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build for MacOS'
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install python3 gawk gnu-sed make gmp mpfr libmpc isl zlib expat texinfo flock libslirp

      - name: Build RISC-V Toolchain
        run: |
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          ./configure --prefix=/opt/riscv --with-languages="c,c++"
          make -j $(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv-toolchain-rv64-newlib-macos
          path: /opt/riscv
